name: Scheduled Fetch Request

on:
  schedule:
    - cron: '*/5 * * * *'   # Runs every 5 minutes

jobs:
  fetch-job:
    runs-on: ubuntu-latest

    steps:
      - name: Send request with curl
        run: curl https://alibaba-pfki.onrender.com/
